const env = import.meta.env;

const {
  VITE_APP_API_URI_BASE: API_URI_BASE,
  VITE_AZURE_CLIENT_ID: AZURE_CLIENT_ID,
  VITE_AZURE_TENANT_ID: AZURE_TENANT_ID,
  VITE_AZURE_REDIRECT_URI: AZURE_REDIRECT_URI,
} = env;

export { API_URI_BASE, AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_REDIRECT_URI };
